In [3]:
import pandas as pd
import sqlite3
import os

In [5]:
DB_PATH = '../data/raw/database.sqlite'
conn = sqlite3.connect(DB_PATH)

tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn)
tables

                name
0    sqlite_sequence
1  Player_Attributes
2             Player
3              Match
4             League
5            Country
6               Team
7    Team_Attributes

In [7]:
query = """
SELECT
    m.id,
    c.name AS country,
    l.name AS league,
    m.season,
    m.date,
    ht.team_long_name AS home_team,
    at.team_long_name AS away_team,
    m.home_team_goal,
    m.away_team_goal
FROM Match m
JOIN Country c ON m.country_id = c.id
JOIN League l ON m.league_id = l.id
JOIN Team ht ON m.home_team_api_id = ht.team_api_id
JOIN Team at ON m.away_team_api_id = at.team_api_id
WHERE c.name = 'England'
ORDER BY m.date
"""

matches = pd.read_sql(query, conn)
conn.close()

matches.to_csv('../data/raw/matches_raw.csv', index=False)

In [9]:
matches.head()

,id,country,league,season,date,home_team,away_team,home_team_goal,away_team_goal
0,1730,England,England Premier League,2008/2009,2008-08-16 00:00:00,Arsenal,West Bromwich Albion,1,0
1,1731,England,England Premier League,2008/2009,2008-08-16 00:00:00,Sunderland,Liverpool,0,1
2,1732,England,England Premier League,2008/2009,2008-08-16 00:00:00,West Ham United,Wigan Athletic,2,1
3,1734,England,England Premier League,2008/2009,2008-08-16 00:00:00,Everton,Blackburn Rovers,2,3
4,1735,England,England Premier League,2008/2009,2008-08-16 00:00:00,Middlesbrough,Tottenham Hotspur,2,1

In [15]:
df = pd.read_csv('../data/raw/matches_raw.csv')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3040 entries, 0 to 3039
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              3040 non-null   int64
 1   country         3040 non-null   object
 2   league          3040 non-null   object
 3   season          3040 non-null   object
 4   date            3040 non-null   object
 5   home_team       3040 non-null   object
 6   away_team       3040 non-null   object
 7   home_team_goal  3040 non-null   int64
 8   away_team_goal  3040 non-null   int64
dtypes: int64(3), object(6)
memory usage: 213.9+ KB

In [19]:
df.head()

,id,country,league,season,date,home_team,away_team,home_team_goal,away_team_goal
0,1730,England,England Premier League,2008/2009,2008-08-16 00:00:00,Arsenal,West Bromwich Albion,1,0
1,1731,England,England Premier League,2008/2009,2008-08-16 00:00:00,Sunderland,Liverpool,0,1
2,1732,England,England Premier League,2008/2009,2008-08-16 00:00:00,West Ham United,Wigan Athletic,2,1
3,1734,England,England Premier League,2008/2009,2008-08-16 00:00:00,Everton,Blackburn Rovers,2,3
4,1735,England,England Premier League,2008/2009,2008-08-16 00:00:00,Middlesbrough,Tottenham Hotspur,2,1

In [21]:
df.describe()

                id  home_team_goal  away_team_goal
count  3040.000000     3040.000000     3040.000000
mean   3248.500000        1.550987        1.159539
std     877.716735        1.311615        1.144629
min    1729.000000        0.000000        0.000000
25%    2488.750000        1.000000        0.000000
50%    3248.500000        1.000000        1.000000
75%    4008.250000        2.000000        2.000000
max    4768.000000        9.000000        6.000000